// `.env.ts` is generated by the `npm run env` command
import env from './.env';

export const environment = {
  production: false,
  version: env.npm_package_version,
  serverUrl: 'http://localhost:8088',
  defaultLanguage: 'pt-BR',
  supportedLanguages: [
    'pt-BR',
    'en-US'
  ]
};
